
name = "zhaopin"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Cloudflare D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "zhaopin"
database_id = "9d2553e2-1b87-472d-812d-3da68d5bacba"

[build]
command = "npx opennextjs-cloudflare build"
